[project]
name = "longevity-knowledge-base"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "openai-agents>=0.4.0",
    "pandas>=2.3.3",
    "rich>=14.2.0",
]
